# Generated by Django 4.1.2 on 2022-12-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
        ('users', '0003_alter_user_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hobby',
        ),
        migrations.AddField(
            model_name='user',
            name='hobby',
            field=models.ManyToManyField(to='workshops.hobby'),
        ),
    ]
