# Generated by Django 4.1.2 on 2022-12-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_hobby_user_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'error': '이미 있는 이메일인데요?'}, max_length=255, unique=True, verbose_name='이메일'),
        ),
    ]
