# Generated by Django 4.1.2 on 2022-12-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_email_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'errors': '이미 있는 이메일인데요?'}, max_length=255, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'errors': '이미 있는 닉네임인데요?'}, max_length=15, unique=True, verbose_name='닉네임'),
        ),
    ]
