# Generated by Django 4.0.6 on 2022-12-19 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workshops.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('address', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=500)),
                ('workshop_image', models.ImageField(upload_to=workshops.utils.rename_imagefile_to_uuid)),
                ('max_guest', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=0, max_digits=1000000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.BigIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_category', to='workshops.hobby')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_host', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='workshop_likes', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_location', to='workshops.location')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('승인', '승인'), ('거절', '거절'), ('대기', '대기')], max_length=3, null=True, verbose_name='신청 유형')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_apply_guest', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_apply', to='workshops.workshop')),
            ],
            options={
                'db_table': 'workshop_apply',
            },
        ),
        migrations.AddField(
            model_name='workshop',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='workshop_participant', through='workshops.WorkshopApply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reveiw_user', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_workshop', to='workshops.workshop')),
            ],
        ),
    ]
