# Generated by Django 4.0.6 on 2022-12-02 02:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_alter_message_options_remove_message_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='ChatRoom',
        ),
        migrations.RenameModel(
            old_name='Message',
            new_name='RoomMessage',
        ),
    ]
